#!/usr/bin/python3

import peewee
from models import *

for i in Temperature.select():
    print(i.time,i.temperature)

for i in Cpu.select():
    print(i.time, i.usage)

for i in Ram.select():
    print(i.time, i.used)
